config/routes.rb
Rails.application.routes.draw do
  get "/checklist", to: "checklist#show"
  get "/checklist/create"
  resources :about, only: [:index]
  resources :types, only: %i[index show]
  resources :locations, only: %i[index show]
  resources :stats, only: [:show]
  get "/pokemons/search", to: "pokemons#search"
  resources :pokemons, only: %i[index show]
  get "/", to: "pokemons#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checklist.rb
#======================
# Checklist
#
# Represents Checklist table in database.
#
# Feilds
# --------------------------
# Title           | String  | Not Required
# Unique Url Id   | String  | Required, Unique
#
# Associations
# --------------------
#
#======================

class Checklist < ApplicationRecord
  validates :unique_url_id, presence: true
  validates :unique_url_id, uniqueness: true

  has_many :listed_pokemons
  has_many :pokemons, through: :listed_pokemons
end

app/models/encounter.rb
#======================
# Location
#
# Represents Encounters table in database.
#
# Feilds
# --------------------------
# Chance  | String  | Required
# Method  | Text    | Required
# Game    | String  | Required, Within (`red`, `blue`, `yellow`)
#
# Associations
# --------------------
# Connects (Many to Many): `Pokemons` <--> `Locations`
# belongs to `Pokemons` & `Locations`
#
#======================

class Encounter < ApplicationRecord
  validates :chance, :method, :game, presence: true
  validates :chance, numericality: true

  belongs_to :pokemon
  belongs_to :location
end

app/models/listed_pokemon.rb
class ListedPokemon < ApplicationRecord
  belongs_to :pokemon
  belongs_to :checklist
end

app/models/location.rb
#======================
# Location
#
# Represents Locations table in database.
#
# Feilds
# --------------------------
# Name:                 | String  | Required
# Img                   | Text    |
#
# Associations
# --------------------
# Has many `Encounters`
# Connected to `Pokemons` via `Encounters`
#
#======================

class Location < ApplicationRecord
  validates :name, presence: true

  has_many :encounters
  has_many :pokemons, through: :encounters
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  #======================
  # Pokemon
  #
  # Represents Pokemon table in database.
  #
  # Feilds
  # --------------------------
  # Name:           | String  | Required
  # Alt_Name        | Text    | Required
  # Pokedex_Number  | Integer | Required, Numeric, Whole Number
  # Description     | Text    | Required
  # Img             | Text    | Required
  # Thumb:          | Text    | Required
  # Color           | String  |
  #
  # Assocations
  # --------------------
  # Has one `Stat`
  # Has many `Encounters`
  # Connected to `Locations` via `Encounters`
  # Has many `Pokemon_types`
  # Connected to `Types` via `Pokemon_Types`
  # Has many `ListedPokemons`
  # Connected to `Checklist` via `ListedPokemons`
  #
  #======================

  has_one :stat
  has_many :encounters
  has_many :locations, through: :encounters
  has_many :pokemon_types
  has_many :types, through: :pokemon_types
  has_many :listed_pokemons
  has_many :checklists, through: :listed_pokemons

  validates :name, :alt_name, :pokedex_number, :description, :img, :thumb, presence: true
  validates :pokedex_number, numericality: { only_integer: true }

  def types_string
    str = types.first.name.capitalize
    str << " / #{types.last.name.capitalize}" if types.count > 1

    str
  end
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type
end

app/models/stat.rb
class Stat < ApplicationRecord
  #======================
  # Pokemon
  #
  # Represents Pokemon table in database.
  #
  # Feilds
  # --------------------------
  # hp:               | Integer | Required, Numeric, Whole Number
  # attack            | Integer | Required, Numeric, Whole Number
  # defense           | Integer | Required, Numeric, Whole Number
  # special_attack    | Integer | Required, Numeric, Whole Number
  # special_defense   | Integer | Required, Numeric, Whole Number
  # speed             | Integer | Required, Numeric, Whole Number
  #
  # Assocations
  # --------------------
  # belongs to one `Pokemon`
  #
  #======================
  belongs_to :pokemon

  validates :hp, :attack, :defense, :special_attack, :special_defense, :speed, presence: true
  validates :hp, :attack, :defense, :special_attack, :special_defense, :speed, Numericality: { only_integer: true }
end

app/models/type.rb
#======================
# Type
#
# Represents Types table in database.
#
# Feilds
# --------------------------
# Name:   | String  | Required, Uniqueness
#
# Assocations
# --------------------
# Has many `Pokemon_Types`
# Connected to `Pokemon` via `Pokemon_Types`
#
#======================
class Type < ApplicationRecord
  has_many :pokemon_types
  has_many :pokemons, through: :pokemon_types
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @pokemons = Pokemon.all
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @prev_pokemon = Pokemon.find_by(id: @pokemon.id - 1)
    @next_pokemon = Pokemon.find_by(id: @pokemon.id + 1)
  end

  def search
    @pokemons = Pokemon.where("name LIKE :query", query: "#{params[:search_term]}%")
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def show
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
  end

  def show
    @type = Type.find(params[:id])
    @pokemons = @type.pokemons
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklist_helper.rb
module ChecklistHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catch Em' All!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>

  <body>
    <section class="section">
      <div class="container">
        <div class="columns is-fullwidth mb-5">
            <div style="width:75px"><%= image_tag "icon/pokeball.png"%></div>
          <div class="column is-one-third">
            <h1 class="title is-1" style="text-align:left"><a href="/">Catch em' All!</a></h1>
          </div>
          <div class="column">
            <h1 class="title is-3" style="text-align:center"><%=link_to "Pokemon", pokemons_path%></h1>
          </div>
          <div class="column">
            <h1 class="title is-3" style="text-align:center"><%=link_to "Locations", locations_path%></h1>
          </div>
          <div class="column">
            <h1 class="title is-3" style="text-align:center"><%=link_to "Types", types_path%></h1>
          </div>
          <div class="column">
            <h1 class="title is-3" style="text-align:center"><%=link_to "About", about_index_path%></h1>
          </div>
        </div>
        <%= yield %>
      <footer style="border-top: 1px solid grey; text-align:center">Created By: Geoff Hodgson | Sept 2020 | <a href="https://github.com/payne1134/CatchEmAll">Github</a></footer>
      </div>
    </section>
  </body>
</html>